config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :posts

    root 'posts#index'

    get  '/signup',  to: 'users#new'
    resources :users

    get 'login', to: 'auth#new'
    post 'login', to: 'auth#create'
    delete 'logout', to: 'auth#destroy'

    resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 125 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    # return unless session[:user_id]
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
      !!current_user
  end

  def require_user
      if !logged_in?
          flash[:danger] = "You must be logged in to perform that action"
          redirect_to root_path
      end
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
    def new

    end

    def create
        user = User.find_by(email: params[:auth][:email].downcase)
        if user && user.authenticate(params[:auth][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in"
            redirect_to posts_path
        else
            flash.now[:danger] = "There was something wrong with your login information"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]

    def index
        @posts = Post.all.order("created_at DESC")
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user = current_user
        if @post.save
            flash[:success] = "Post was successfully created"
            redirect_to post_path(@post)
        else
            render 'new'
        end
    end

    def show
    end

    def update
        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end

    def edit
    end

    def destroy
        @post.destroy
        redirect_to root_path
    end

    private

    def find_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:title, :content, :category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render 'new'
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <% flash.each do |name, msg| %>
                <div class='alert alert-<%= "#{name}"%>'>
                    <a href="" class="close" data-dismiss="alert">&#215;</a>
                    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- <a class="navbar-brand" id="logo" href="#">Alpha blog</a> -->
            <%= link_to "Simple blog", root_path, class: "navbar-brand", id: "logo" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><%= link_to "Posts", posts_path %></li>
                <li><%= link_to "Users", users_path %></li>
                <% if logged_in? %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "New article", new_post_path %></li>
                        <% Category.all.each do |category| %>
                            <li><%= link_to "#{category.name}", category_path(category) %></li>
                        <% end %>
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="#">Separated link</a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="#">One more separated link</a>
                        </li>
                    </ul>
                </li>
                <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                <li><%= link_to 'Log out', logout_path, method: :delete %></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile
                        <%= current_user.username if current_user.username %>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <%= link_to "Edit your profile", edit_user_path(current_user) %>
                        </li>
                        <li>
                            <%= link_to "View your profile", user_path(current_user) %>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="#">Separated link</a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="#">One more separated link</a>
                        </li>
                    </ul>
                </li>
            <% else %>
                <li><%= link_to 'Log in', login_path %></li>
                <li><%= link_to 'Sign up', signup_path %></li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <%= form_for @post, :html => {class: "form-horizontal", role: "form"} do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :title %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :category_id %>
                </div>
                <div class="col-sm-8">
                    <%= f.collection_select :category_id, Category.all, :id, :name, {}, {class: "form-control"} %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :content %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_area :content, class: "form-control", rows: 6, placeholder: "Description of article", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-5 col-sm-3">
                    <%= f.submit "Create new", class: "btn btn-primary" %>
                    <%= link_to 'Cancel and back', posts_path, class: "btn btn-danger" %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>All Post</h1>

<h2><%= link_to "Create post", new_post_path, class: "btn btn-primary" %></h2>

<% @posts.each do |post| %>

<div class="row">
    <div class="col-xs-8">
        <div class="col-xs-offset-2">
            <div class="well well-lg">
                <div class="post-title">
                    <h2><%= link_to post.title, post_path(post) %></h2>
                </div>
                <div class="post-body">
                    <p><%= truncate(post.content, length: 100) %></p>
                    <div class="post-meta-details">
                        
                        <small>Created by: <%= post.user.username if post.user %></small>
                        <small>Created at: <%= time_ago_in_words(post.created_at) %> ago</small>
                        <small>Updated at: <%= time_ago_in_words(post.updated_at) %></small>
                        <small>Category: <%= post.category.name %></small>
                    </div>
                </div>
                <div class="post-actions">
                    <%= link_to "Edit this post", edit_post_path(post), class: "btn btn-xs btn-primary" %>
                    <%= link_to "Delete this post", post_path(post), method: :delete, class: "btn btn-xs btn-danger", data: {confirm: "Are you sure?"} %>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<%= link_to "Edit Post", edit_post_path(@post), class: "btn btn-danger" %>
<%= link_to "Delete post", post_path(@post), method: :delete, class: "btn btn-danger"%>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, :html => {class: "form-horizontal", role: "form"} do |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :username %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :email %>
            </div>
            <div class="col-sm-8">
                <%= f.email_field :email, class: "form-control", placeholder: "Email", autofocus: true %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :password %>
            </div>
            <div class="col-sm-8">
                <%= f.password_field :password, class: "form-control", placeholder: "Password", autofocus: true %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :password_confirmation  %>
            </div>
            <div class="col-sm-8">
                <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password", autofocus: true %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-5 col-sm-3">
                <%= f.submit "Signup", class: "btn btn-primary" %>
            </div>
        </div>
    <% end %>
  </div>
</div>